import { Inter } from "next/font/google";
import "./globals.css";
import TopNavigation from '@/components/TopNavigation';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App FE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}  suppressHydrationWarning={true}>
          <TopNavigation />
          {children}
      </body>
    </html>
  );
}
